### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by michel404** [mean00/DSO_STM32Duino#5]
First of all: think this is an awesome project! I'm really impressed by the work you've done :smile: 

I was able to install the custom firmware using your compiled (vanilla) binaries and the the open source project [stm32flash](https://sourceforge.net/p/stm32flash/wiki/Home/) by running `./stm32flash -b 115200 -v -w Dso150STM32F103_vanilla.bin /dev/ttyUSB0`. As this was quite simple, you may consider to include it in your installation instructions.

Secondly, I was wondering whether you intend to get the rotary encoder to work better without hardware mod. Do you think that is possible? Do you intent to implement it?

And more generally speaking: can you say anything about features you plan to add in the future?

**Comment by mean00** [comment]
Hi, 
Thank you for the feedback.
The rotary encoder issue is due to how the original DSO hw is done
They are using the same pins as output to drive the screen and as input to read the buttons/rotary encoder
As a result, when the screen is being refreshed, the buttons/RE are ignored and  you'll loose some  of them
It's possible to improve it by refreshing the screen "slowly" i.e. by small chunks, but it's ugly
The mod to use different pins is very simple and really effective.

As far as features go :
- There is some preliminary work to setup & get the data from/to a PC/MAC through USB. 
- The triggering needs a bit of love to avoid missing triggers in some rare cases. 
- Better averaging when using slow timebase to avoid stroboscopic effect

It's not for the near futur, i'm quite happy with how it is now, especially with the experimental "dump to csv/dump to png" usb function.

**Comment by michel404** [comment]
I intend to try out other custom firmware as well ([this one](https://github.com/michar71/Open-DSO-150), maybe others), so I am a bit reluctant with hw mods :wink: 

Thanks for sharing your thoughts and plans!
